name: Generate data daily

on:
  push:
  schedule:
    # The current command has to be replaced by the line below (now it doesn't do anything)
    # - cron: "30 19 * * *"
    - cron: "30 25 * * *"

defaults:
  run:
    working-directory: data

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install
      - run: node index.js
      - name: Push changes
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: 'main'
